version: '2'
services:
    nginx:
        container_name: nginx
        image: nginx:1.16.1-alpine
        ports:
            - '8080:8080'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    frontend:
        container_name: frontend
        image: node:10
        ports:
            - '3000:3000'
        volumes:
            - ./node_modules:/work/node_modules
            - ./:/work
        working_dir: '/work'
        command: ["bash"]
        stdin_open: true
        tty: true